---
name: consulagent

# update: section explicitly missing so operator must choose operators/firsttime.yml or operators/existing.yml

instance_groups:
- name: consul
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 5GB 
  networks: [{name: default}]
  jobs:
  - release: consul
    name: consul
    # provides:
    #   consul_servers:
    #     as: consul_leaders
    #     shared: true
    consumes:
      consul_servers: { from: consul_leaders, deployment: consul}
    properties:
      consul:
        ssl_ca: ((consul-ca.ca))
        ssl_cert: ((consul-tls.certificate))
        ssl_key: ((consul-tls.private_key))
        server: false
        verify_incoming: false
        domain: consul.metaverse.l11.com

variables:
- name: consul-ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: consul-tls
  type: certificate
  options:
    ca: consul-ca
    common_name: consul
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.metaverse.l11.com"

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

# update: section explicitly missing so operator must choose operators/firsttime.yml or operators/existing.yml


releases:
- name: consul
  version: 24.0.0+dev.7
